### ISSUE TITLE
sc2 _restart stuck in a long loop

### ISSUE THREAD

**Issue by DrZero0** [oxwhirl/smacv2#2]
Hi, I am interested in your SMACv2 that it makes the original SMAC more challenging but I encountered some problems. 
When I tried to run on some original maps like "3m" to use the stochastic spawn location and sectional observation, I found that my program was always stuck in a while loop in the function self._kill_all_units(). And always receive: 

```bash
RequestQuit command received.
Closing Application...
DataHandler: unable to parse websocket frame.
CloseHandler: 127.0.0.1:46776 disconnected
Starting up...
Startup Phase 1 complete
[INFO 15:27:44] absl Shutdown gracefully.
[INFO 15:27:44] absl Shutdown with return code: -15
```

In smac/env/starcraft2/starcraft2.py
``` python
def _restart(self):
    """Restart the environment by killing all units on the map.
    There is a trigger in the SC2Map file, which restarts the
    episode when there are no units left.
    """
    try:
        self._kill_all_units()
    except (protocol.ProtocolError, protocol.ConnectionError):
        self.full_restart()

def _kill_all_units(self):
    """Kill all units on the map. Steps controller and so can throw
    exceptions"""
    units = [unit.tag for unit in self._obs.observation.raw_data.units]
    self._kill_units(units)
    # check the units are dead
    units = len(self._obs.observation.raw_data.units)
    while len(self._obs.observation.raw_data.units) > 0:
        self._controller.step(2)
        self._obs = self._controller.observe()
```
On map "3m", "len(self._obs.observation.raw_data.units)" is always 6. Is it because that it does not further kill units in the while loop? After I replace the _restart and _kill_all_units functions with the code from the original smac, everything is fine.

**Comment by benellis3** [comment]
Hi. Thanks very much for your interest in SMACv2! Apologies for this problem, I am updating the documentation as we speak -- it is not super clear at the moment.

As you have observed, SMAC maps crash when started in SMACv2. This is a consequence of changes made to trigger random unit generation. Because we have a different team at the start of each episode, we must create units at each new episode. We may restore backwards compatibility at some point if there is enough demand, but it is not high on the priority list at the moment. 

For an example config and running command see [1] and [2]. If you want to recreate 3m within SMACv2, that is also fairly easy to accomplish. Using the example config in [1], you could make a few changes. First you would need to set conic_fov to False, then delete the section on 'start_positions', and then change the `unit_types` list to just be `marine` and the weight to be `1.0`. You would also need to change n_units and n_enemies in the various places to 3.

I hope this helps and please let me know if you encounter any more difficulties. I am currently trying to improve the documentation and would appreciate the feedback so I can help iron out issues people have!

[1] https://github.com/oxwhirl/pymarl-dev/blob/smac-v2/src/config/envs/sc2_gen_protoss.yaml
[2] https://github.com/oxwhirl/pymarl-dev/blob/smac-v2/run.sh#L57

**Comment by DrZero0** [comment]
Thanks for your quick response! Now I understand why SMAC maps crash but it appears that I do not have access to the links attached. 

I am not sure but it seems that the solution you proposed is only suitable for SMAC maps with units of the same type? It may not be high on the priority list but I still hope SMAC maps with random start positions and conic observation can be compatible with SMACv2. This can be taken as a crucial update to original SMAC maps that introduces more stochasticity and partial observability which would make them more challenging for agents to communicate and cooperate. 

Thanks again for your hard work and contribution. I am looking forward to your reply.

**Comment by benellis3** [comment]
Sorry -- linked you to the private repo 🤦‍♂️ . To clarify, you **can** recreate SMAC maps in SMACv2, only with the restriction that asymmetric scenarios (different enemy/ally units) will not work. If you follow the steps I described (changing the spawned unit types in the below config), you will get exactly 3m with random start positions and conic FOV. 

Asymmetric scenarios are only not possible now because we restrict teams to consist of the same units to balance the difficulty. This could be rectified without too much effort -- let me know if you want to do this and I will point you at some code links. 

SMACv2 config:
https://github.com/benellis3/mappo/blob/main/src/config/envs/sc2_gen_terran.yaml#L45
Example run command:
https://github.com/benellis3/mappo/blob/main/run.sh#L57

**Comment by DrZero0** [comment]
Thanks! To simplify, I wonder what I should do if I want to run maps like `2s3z` and `2c_vs_64zg` with random start positions and conic FOV. 

Thank you for being patient with me, and I look forward to your guidance.

**Comment by benellis3** [comment]
Hi. I got pretty busy so apologies this has been sitting here for a while. Now that I think about I am not sure you can recreate either of these scenarios. I will take a look next week and see how tricky fixing this is. If it's still an issue and I haven't got back to you in a while just post a reminder here -- I have a lot on right now so it's probably slipped through the cracks! In principle it shouldn't be too difficult, but I can't make any promises!

**Comment by benellis3** [comment]
Closing this to clean things up. Let me know if it is still and issue and I'll reopen.
