### ISSUE TITLE
Failed to render the field of view in cones 

### ISSUE THREAD

**Issue by LLLLLH76** [oxwhirl/smacv2#4]
Hi, I am interested in your SMACv2 that it makes the original SMAC more challenging but I encountered some problems. I tried to save a replay to examine if the agents really learn to ‘snap’ their cone, however, no lines are displayed like the ones in your README file. Then I added the `render_fovs()` function in the `save_replay()` function but it was still not working. Is there a way to correctly render them? Thanks!

**Comment by benellis3** [comment]
There is an explanation of this in the README here: https://github.com/oxwhirl/smacv2#why-are-the-fov-cones-not-visible-in-my-replay

As a solution to this, you can run the evaluation on a machine with a version of starcraft that you can watch, and then slow down the main loop so that it is approximately real-time (e.g. by adding `time.sleep`). This isn't ideal obviously, but unfortunately there is not a lot we can do to fix this -- debug elements aren't saved in replays 😢 in SC2. Thanks for the question! Let us know if there's anything else we can help with.

**Comment by LLLLLH76** [comment]
I get it. Thanks!
